### ISSUE TITLE
MacOS Pro(13-inch,M1,2020) BigSur 11.2 游玩doodle_jump无法移动

### ISSUE THREAD

**Issue by 54853315** [XadillaX/node-sfml-demos#1]
node : v15.11.0 16.12.0

游戏运行成功，无法移动，脸滚键盘了。

**Comment by XadillaX** [comment]
手头没有 M1，无法复现。

你的 Node.js 是 M1 的还是 x64 的？因为这边用的动态链接库是 SFML 的 macOS 动态链接库，不太确认这些 *.dylib 可以正常运行在 M1 的 arm 架构下。

如果 M1 跑 Node.js 是 x64 兼容模式，目测是可以的。如果 Node.js 是 M1 的 arm 版，那么可能是因为 arm 的可执行文件去加载 x64 的动态链接库导致的。

**Comment by 54853315** [comment]
> 手头没有 M1，无法复现。
> 
> 你的 Node.js 是 M1 的还是 x64 的？因为这边用的动态链接库是 SFML 的 macOS 动态链接库，不太确认这些 *.dylib 可以正常运行在 M1 的 arm 架构下。
> 
> 如果 M1 跑 Node.js 是 x64 兼容模式，目测是可以的。如果 Node.js 是 M1 的 arm 版，那么可能是因为 arm 的可执行文件去加载 x64 的动态链接库导致的。

https://github.com/nodejs/build/issues/2474#issuecomment-801065366

node 15开始支持arm，不需要Rosetta2 转x86 。那有可能是你说的加载异常问题了（虽然在npm run后 没有报错），我估计sfml那边应该会有更合适的issue。

**Comment by XadillaX** [comment]
https://github.com/SFML/SFML/pull/1750
